const data={
  units:[
    {id:'U-1048',product:'iPhone 16 Pro',variant:'256 GB · Titanio natural',code:'356821•••904',state:'STOCK',cost:1080,price:1320,client:'—',seller:'—',date:'29 ago 2026'},
    {id:'U-1047',product:'Galaxy S26 Ultra',variant:'512 GB · Negro',code:'358940•••118',state:'REPARTO',cost:940,price:1190,client:'Matías R.',seller:'Lucía',date:'29 ago 2026'},
    {id:'U-1046',product:'GoPro MAX',variant:'Negro',code:'GP-MX-00931',state:'STOCK',cost:420,price:540,client:'—',seller:'—',date:'28 ago 2026'},
    {id:'U-1045',product:'AirPods Pro',variant:'USB-C · Blanco',code:'AP-PRO-7712',state:'ENTREGADA',cost:180,price:245,client:'Carla S.',seller:'Diego',date:'28 ago 2026'},
    {id:'U-1044',product:'iPhone 16',variant:'128 GB · Negro',code:'351180•••672',state:'REPARTO',cost:760,price:960,client:'Nicolás F.',seller:'Lucía',date:'27 ago 2026'},
    {id:'U-1043',product:'Galaxy S25',variant:'256 GB · Azul',code:'352511•••021',state:'ENTREGADA',cost:610,price:790,client:'Martina A.',seller:'Diego',date:'27 ago 2026'}
  ],
  orders:[
    {id:'#421',supplier:'Distribuidor Norte',date:'29 ago',units:6,status:'ENVÍO',total:5480},
    {id:'#420',supplier:'Apple Partner BA',date:'28 ago',units:4,status:'RECIBIDO',total:4320},
    {id:'#419',supplier:'Tecno Import',date:'26 ago',units:9,status:'STOCK',total:6190},
    {id:'#418',supplier:'Distribuidor Norte',date:'24 ago',units:8,status:'STOCK',total:7740}
  ],
  products:[['iPhone 16 Pro','Apple · Celulares','18'],['Galaxy S26 Ultra','Samsung · Celulares','11'],['GoPro MAX','GoPro · Cámaras','4'],['AirPods Pro','Apple · Audio','9']],
  routes:[
    {name:'Ruta Norte',driver:'Lucía · 4 unidades',stops:[['Matías R.','Galaxy S26 · 16:30'],['Nicolás F.','iPhone 16 · 17:15']]},
    {name:'Ruta Centro',driver:'Diego · 3 unidades',stops:[['Carla S.','AirPods Pro · 15:00'],['Martina A.','Galaxy S25 · 16:00']]},
    {name:'Retiros',driver:'Local · 2 unidades',stops:[['Federico L.','iPhone 16 Pro · 18:00']]}
  ]
};

const icons={money:'$',box:'▣',cart:'↓',route:'↗',check:'✓',chart:'⌁',people:'◎',tag:'◇'};
const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const badge=s=>`<span class="badge ${s==='STOCK'||s==='RECIBIDO'?'green':s==='REPARTO'||s==='ENVÍO'?'blue':s==='ENTREGADA'?'violet':'muted-badge'}">${s}</span>`;
const head=(kicker,title,description,action='')=>`<header class="page-head"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${description}</p></div>${action||'<div class="date-block"><b>Operación estable</b>31 agosto 2026 · 14:32</div>'}</header>`;
const metric=(label,value,detail,icon,color='var(--blue)')=>`<article class="metric" style="--accent:${color}"><div class="metric-top"><span>${label}</span><i class="metric-icon">${icon}</i></div><strong>${value}</strong><small>${detail}</small></article>`;
const unitRows=units=>units.map(u=>`<tr data-unit="${u.id}"><td class="mono">${u.id}</td><td class="product-cell"><strong>${u.product}</strong><small>${u.variant}</small></td><td class="mono">${u.code}</td><td>${badge(u.state)}</td><td>${u.client}</td><td>${money(u.price)}</td></tr>`).join('');

function inicio(){return `<div class="view">${head('Centro de mando','Buen día, Diego.','Tu operación, resumida en decisiones claras.')}
<section class="metrics">${metric('Ventas de hoy','$ 4.620','6 unidades entregadas',icons.money)}${metric('Ganancia','$ 1.140','Margen estimado del día',icons.chart,'var(--green)')}${metric('Compras','$ 5.480','Pedido #421 en tránsito',icons.cart,'var(--violet)')}${metric('Unidades activas','34','28 en stock · 6 en ruta',icons.box,'var(--cyan)')}</section>
<section class="dashboard-grid"><article class="panel"><header class="panel-head"><div><span class="eyebrow">ACU · Flujo vivo</span><h2>Movimiento de unidades</h2></div><button class="link-btn" data-go="stock">Ver stock →</button></header><div class="flow"><button class="flow-node" data-go="compras"><i>↓</i><span><small>Origen</small><span>Compras</span></span><b>4</b></button><i class="connector"></i><button class="flow-node active" data-go="stock"><i>▣</i><span><small>Disponible</small><span>Stock</span></span><b>28</b></button><i class="connector"></i><button class="flow-node" data-go="reparto"><i>↗</i><span><small>En movimiento</small><span>Reparto</span></span><b>6</b></button><i class="connector"></i><button class="flow-node" data-go="ventas"><i>✓</i><span><small>Ciclo cerrado</small><span>Entregadas</span></span><b>11</b></button></div><p class="caption">Cada número representa unidades físicas trazables, no cantidades de stock independientes.</p></article>
<article class="panel"><header class="panel-head"><div><span class="eyebrow">Prioridad</span><h2>Requiere atención</h2></div><span class="badge amber">3 señales</span></header><div class="attention"><span class="orbit"><b>3</b></span><div><strong>Hay decisiones pendientes</strong><p>Dos unidades esperan asignación y un pedido necesita completar números de serie.</p></div></div><button class="primary-btn" data-go="compras">Resolver pendientes →</button></article></section>
<div class="quickbar"><span>Acciones rápidas</span><button data-demo="Compra preparada">＋ Registrar compra</button><button data-demo="Venta preparada">＋ Nueva venta</button><button data-go="datos">Administrar datos</button></div></div>`}

function compras(){return `<div class="view">${head('Abastecimiento','Compras','Pedidos a proveedores y nacimiento de nuevas unidades.','<button class="primary-btn" data-demo="Nuevo pedido iniciado">＋ Nuevo pedido</button>')}<section class="summary-row">${metric('En tránsito','6','Unidades por recibir',icons.route)}${metric('Recibidas esta semana','21','Identidades físicas creadas',icons.box,'var(--green)')}${metric('Inversión del mes','$ 23.730','Costos registrados',icons.money,'var(--violet)')}</section><div class="toolbar"><input class="search" placeholder="Buscar pedido o proveedor…"><select class="filter"><option>Todos los estados</option><option>En envío</option><option>Recibidos</option></select></div><div class="table-wrap"><table><thead><tr><th>Pedido</th><th>Proveedor</th><th>Fecha</th><th>Unidades</th><th>Estado</th><th>Total</th></tr></thead><tbody>${data.orders.map(o=>`<tr data-demo="Abriendo ${o.id}"><td class="mono">${o.id}</td><td class="product-cell"><strong>${o.supplier}</strong><small>Compra registrada</small></td><td>${o.date}</td><td>${o.units}</td><td>${badge(o.status)}</td><td>${money(o.total)}</td></tr>`).join('')}</tbody></table></div></div>`}
function ventas(){return `<div class="view">${head('Cierre comercial','Ventas','Cada venta conserva la identidad de la unidad, el cliente y el vendedor.','<button class="primary-btn" data-demo="Flujo de nueva venta abierto">＋ Nueva venta</button>')}<section class="metrics">${metric('Hoy','$ 4.620','6 ventas confirmadas',icons.money)}${metric('Pendientes de cobro','2','Unidades entregadas',icons.check,'var(--amber)')}${metric('Comisiones','$ 318','Acumulado del día',icons.people,'var(--green)')}${metric('Ticket promedio','$ 770','Últimas 30 ventas',icons.chart,'var(--violet)')}</section><div style="height:14px"></div><div class="table-wrap"><table><thead><tr><th>Unidad</th><th>Producto</th><th>IMEI / código</th><th>Estado</th><th>Cliente</th><th>Venta</th></tr></thead><tbody>${unitRows(data.units.filter(u=>u.state==='ENTREGADA'))}</tbody></table></div></div>`}
function stock(){return `<div class="view">${head('28 unidades disponibles','Stock','Consulta individual de equipos, costos, códigos y estado actual.','<button class="primary-btn" data-demo="Ingreso manual preparado">＋ Ingresar unidad</button>')}<div class="toolbar"><input id="stock-search" class="search" placeholder="Buscar producto, IMEI o código…"><select class="filter"><option>Todos los productos</option><option>Apple</option><option>Samsung</option></select><span class="badge green">Actualizado ahora</span></div><div class="table-wrap"><table><thead><tr><th>Unidad</th><th>Producto</th><th>IMEI / código</th><th>Estado</th><th>Cliente</th><th>Precio</th></tr></thead><tbody id="unit-body">${unitRows(data.units.filter(u=>u.state==='STOCK'))}</tbody></table></div></div>`}
function reparto(){return `<div class="view">${head('Logística diaria','Reparto','Rutas, responsables y unidades preparadas para entrega.','<button class="primary-btn" data-demo="Planificación diaria abierta">Planificar reparto</button>')}<section class="summary-row">${metric('En ruta','6','Unidades con responsable',icons.route)}${metric('Entregas de hoy','11','9 pagos verificados',icons.check,'var(--green)')}${metric('Próximo cierre','19:30','Congela el prorrateo',icons.chart,'var(--amber)')}</section><section class="route-grid">${data.routes.map(r=>`<article class="route-card"><header class="route-card-head"><div><h3>${r.name}</h3><p>${r.driver}</p></div><span class="badge blue">Activa</span></header>${r.stops.map((s,i)=>`<div class="route-stop"><span class="stop-num">${i+1}</span><div><strong>${s[0]}</strong><small>${s[1]}</small></div></div>`).join('')}<button class="secondary-btn" style="width:100%;margin-top:12px" data-demo="Ruta copiada para WhatsApp">Copiar para WhatsApp</button></article>`).join('')}</section></div>`}
function datos(){return `<div class="view">${head('Datos maestros','Datos','La información que alimenta compras, ventas, stock y reparto.')}<section class="data-grid">${[['Productos','284 referencias activas',icons.box],['Proveedores','12 contactos comerciales',icons.cart],['Clientes','418 perfiles registrados',icons.people],['Vendedores','6 integrantes activos',icons.tag]].map((x,i)=>`<button class="data-card" data-demo="Abriendo ${x[0].toLowerCase()}"><i>${x[2]}</i><strong>${x[0]}</strong><span>${x[1]}. Administrá información, contacto y estado.</span><small>ADMINISTRAR →</small></button>`).join('')}</section><div style="height:14px"></div><article class="panel"><header class="panel-head"><div><span class="eyebrow">Calidad de datos</span><h2>Catálogo de productos</h2></div><button class="link-btn" data-demo="Catálogo completo abierto">Ver catálogo →</button></header><div class="table-wrap"><table><thead><tr><th>Producto</th><th>Familia</th><th>Unidades</th><th>Integridad</th></tr></thead><tbody>${data.products.map((p,i)=>`<tr data-demo="Editando ${p[0]}"><td class="product-cell"><strong>${p[0]}</strong><small>Código maestro ${i===2?'pendiente':'verificado'}</small></td><td>${p[1]}</td><td>${p[2]}</td><td>${i===2?'<span class="badge amber">Revisar</span>':'<span class="badge green">Completo</span>'}</td></tr>`).join('')}</tbody></table></div></article></div>`}
function reportes(){return `<div class="view">${head('Lectura del negocio','Reportes','Indicadores derivados de las mismas unidades y sus relaciones.')}<section class="metrics">${metric('Facturación mensual','$ 48.320','+12% vs. mes anterior',icons.money)}${metric('Margen bruto','$ 11.870','24,6% sobre ventas',icons.chart,'var(--green)')}${metric('Rotación de stock','18 días','Promedio por unidad',icons.box,'var(--cyan)')}${metric('Entregas a tiempo','94%','Últimos 30 días',icons.check,'var(--violet)')}</section><div style="height:14px"></div><section class="report-grid"><article class="panel"><header class="panel-head"><div><span class="eyebrow">Últimos 30 días</span><h2>Ventas por categoría</h2></div><select class="filter"><option>Unidades</option><option>Facturación</option></select></header><div class="bars">${[['Celulares',82,41],['Audio',54,27],['Cámaras',38,19],['Accesorios',26,13]].map(x=>`<div class="bar-row"><span>${x[0]}</span><div class="bar-track"><div class="bar-fill" style="width:${x[1]}%"></div></div><b>${x[2]}%</b></div>`).join('')}</div></article><article class="panel"><header class="panel-head"><div><span class="eyebrow">Trazabilidad</span><h2>Actividad reciente</h2></div></header><div class="activity"><div class="activity-item"><time>14:18</time><div><strong>Unidad U-1048 ingresó a stock</strong><small>Pedido #421 · iPhone 16 Pro</small></div></div><div class="activity-item"><time>13:42</time><div><strong>Entrega confirmada</strong><small>U-1045 · pago verificado</small></div></div><div class="activity-item"><time>12:06</time><div><strong>Ruta Norte iniciada</strong><small>4 unidades · responsable Lucía</small></div></div></div></article></section></div>`}

const views={inicio,compras,ventas,reparto,stock,datos,reportes};
let current='inicio';
const app=document.querySelector('#app');
function render(page){current=page;app.innerHTML=views[page]();document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));app.focus();bindDynamic()}
function bindDynamic(){document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.go)));document.querySelectorAll('[data-demo]').forEach(b=>b.addEventListener('click',()=>notify(b.dataset.demo)));document.querySelectorAll('[data-unit]').forEach(row=>row.addEventListener('click',()=>openUnit(row.dataset.unit)));const search=document.querySelector('#stock-search');if(search)search.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelector('#unit-body').innerHTML=unitRows(data.units.filter(u=>u.state==='STOCK'&&`${u.product} ${u.code} ${u.variant}`.toLowerCase().includes(q)));bindDynamic()})}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.page)));
document.querySelector('.mobile-menu').addEventListener('click',()=>document.querySelector('.nav').classList.toggle('open'));
const modal=document.querySelector('#modal');
function openUnit(id){const u=data.units.find(x=>x.id===id);if(!u)return;document.querySelector('#modal-title').textContent=`${u.product} · ${u.id}`;document.querySelector('#modal-content').innerHTML=`<div class="detail-grid">${[['Estado',badge(u.state)],['IMEI / código',u.code],['Variante',u.variant],['Cliente',u.client],['Vendedor',u.seller],['Precio de venta',money(u.price)]].map(x=>`<div class="detail-item"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('')}</div><div class="unit-timeline"><span class="eyebrow" style="margin-bottom:18px">Ciclo de vida de la unidad</span><div class="timeline-step"><span class="timeline-dot"></span><div><strong>Pedido registrado</strong><small>Origen trazable · costo ${money(u.cost)}</small></div></div><div class="timeline-step"><span class="timeline-dot"></span><div><strong>Ingreso físico confirmado</strong><small>${u.date} · identidad individual creada</small></div></div><div class="timeline-step"><span class="timeline-dot"></span><div><strong>Estado actual: ${u.state}</strong><small>Última actualización simulada hace 18 minutos</small></div></div></div>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
document.querySelector('.modal-close').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
let toastTimer;function notify(text){const toast=document.querySelector('#toast');toast.textContent=`${text} · interacción demostrativa`;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}
render('inicio');
