"use client";
import { useMemo, useState } from "react";
import { BarChart3, CircleDollarSign, Download, Info, LayoutDashboard, PackageCheck, Save, Trash2, TrendingUp } from "lucide-react";
import AnalyticsChart from "@/components/ui/AnalyticsChart/AnalyticsChart";
import MetricCard from "@/components/ui/MetricCard/MetricCard";
import PageHeader from "@/components/ui/PageHeader/PageHeader";
import { useAnalytics } from "@/contexts/AnalyticsContext";
import { aggregate, dimensionLabels, filterAnalytics, formatMetric, metricLabels } from "@/lib/analytics";
import { useProgram } from "@/contexts/ProgramContext";
import type { ChartType, Dimension, Metric, ReportConfig } from "@/types/analytics";
import styles from "./ReportsScreen.module.css";

const initial:ReportConfig={id:"builder",title:"Ventas por categoría",dimension:"category",metric:"sales",chartType:"bar",state:"TODOS"};
export default function ReportsScreen(){
 const [config,setConfig]=useState(initial);const {charts,addChart,removeChart,busy,error}=useAnalytics(); const {analytics}=useProgram();
 const data=useMemo(()=>aggregate(analytics,config),[analytics,config]);const rows=useMemo(()=>filterAnalytics(analytics,config),[analytics,config]);
 const sold=rows.filter(r=>r.state==="REPARTO"||r.state==="ENTREGADA");
 const revenue=sold.reduce((s,r)=>s+r.sale,0),cost=sold.reduce((s,r)=>s+r.cost,0),commission=sold.reduce((s,r)=>s+r.commission,0),profit=revenue-cost-commission;
 const update=<K extends keyof ReportConfig>(key:K,value:ReportConfig[K])=>setConfig((old)=>({...old,[key]:value}));
 function exportCsv(){
   const cell=(value:string|number)=>{const text=String(value);const safe=typeof value==="string"&&/^[=+@\\-\\t\\r]/.test(text)?"'"+text:text;return '"'+safe.replaceAll('"','""')+'"';};
   const head=["Unidad","Fecha","Estado","Producto","Marca","Cliente","Vendedor","Costo","Venta","Comision","Pago"].map(cell).join(",");
   const body=rows.map(r=>[r.id,r.date,r.state,r.product,r.brand,r.client,r.seller,r.cost,r.sale,r.commission,r.paid?"Sí":"No"].map(cell).join(",")).join("\r\n");
   const url=URL.createObjectURL(new Blob(["\uFEFF"+head+"\r\n"+body],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="pgl-pulse-reporte.csv";a.click();URL.revokeObjectURL(url);
 }

 return <div className={`view ${styles.page}`}><PageHeader eyebrow="Explorador analítico" title="Reportes" description="Combiná dimensiones, métricas y estados para responder preguntas operativas." action={<button className={`primary-btn ${styles.headAction}`} disabled={busy || !config.title.trim() || config.title.length>150} onClick={()=>void addChart(config)}><LayoutDashboard size={15}/> Agregar al Dashboard</button>}/>
 {error&&<p role="alert" className="operation-error">{error}</p>}<section className={styles.kpis}><MetricCard label="Facturación" value={formatMetric(revenue,"sales")} detail="Ventas del filtro seleccionado" icon={<CircleDollarSign size={17}/>}/><MetricCard label="Ganancia" value={formatMetric(profit,"profit")} detail="Luego de costos y comisiones" icon={<TrendingUp size={17}/>} color="var(--green)"/><MetricCard label="Unidades" value={String(rows.length)} detail="Trazabilidad total" icon={<PackageCheck size={17}/>} color="var(--cyan)"/><MetricCard label="Pagos verificados" value={`${(sold.length ? Math.round(sold.filter(r=>r.paid).length/sold.length*100) : 0)}%`} detail="Sobre las ventas del filtro" icon={<BarChart3 size={17}/>} color="var(--violet)"/></section>
 <section className={styles.builder}><aside className={`panel ${styles.controls}`}><div><span className="eyebrow">Constructor</span><h2 style={{margin:"5px 0 0",fontSize:17}}>Configurar informe</h2></div><div className={styles.control}><label>Título</label><input value={config.title} onChange={e=>update("title",e.target.value)}/></div><div className={styles.controlRow}><div className={styles.control}><label>Agrupar por</label><select value={config.dimension} onChange={e=>update("dimension",e.target.value as Dimension)}>{Object.entries(dimensionLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div><div className={styles.control}><label>Métrica</label><select value={config.metric} onChange={e=>update("metric",e.target.value as Metric)}>{Object.entries(metricLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div></div><div className={styles.controlRow}><div className={styles.control}><label>Estado</label><select value={config.state} onChange={e=>update("state",e.target.value)}><option value="TODOS">Todos</option><option>RETIRADO</option><option>STOCK</option><option>REPARTO</option><option>ENTREGADA</option></select></div><div className={styles.control}><label>Visualización</label><select value={config.chartType} onChange={e=>update("chartType",e.target.value as ChartType)}><option value="bar">Barras</option><option value="line">Línea</option><option value="donut">Dona</option></select></div></div><button className={`primary-btn ${styles.save}`} disabled={busy || !config.title.trim() || config.title.length>150} onClick={()=>void addChart(config)}><Save size={14}/> Agregar al Dashboard</button><div className={styles.hint}><Info size={14}/> Datos de Supabase. Los importes de venta y ganancia corresponden a unidades vendidas; el costo incluye el envío.</div></aside>
 <article className={`panel ${styles.preview}`}><header className={styles.previewHead}><div><span className="eyebrow">Vista previa · {rows.length} unidades</span><h2>{config.title}</h2></div><div className={styles.previewActions}><button className={styles.iconButton} onClick={exportCsv}><Download size={14}/> Exportar CSV</button></div></header><AnalyticsChart data={data} type={config.chartType} metric={config.metric}/></article></section>
 <section className="panel"><header className="panel-head"><div><span className="eyebrow">Detalle consultable</span><h2>Unidades del informe</h2></div><span className="badge blue">{rows.length} resultados</span></header><div className={`table-wrap ${styles.detailTable}`}><table><thead><tr><th>Unidad</th><th>Fecha</th><th>Estado</th><th>Producto</th><th>Cliente</th><th>Vendedor</th><th>Costo</th><th>Venta</th><th>Pago</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="mono">{r.id}</td><td>{r.date}</td><td><span className={`badge ${r.state==="ENTREGADA"?"green":r.state==="STOCK"?"blue":"violet"}`}>{r.state}</span></td><td className="product-cell"><strong>{r.product}</strong><small>{r.brand} · {r.category}</small></td><td>{r.client}</td><td>{r.seller}</td><td>{formatMetric(r.cost,"cost")}</td><td>{formatMetric(r.sale,"sales")}</td><td>{r.paid?"Sí":"No"}</td></tr>)}</tbody></table></div></section>
 <section className={`panel ${styles.saved}`}><header className="panel-head"><div><span className="eyebrow">Dashboard</span><h2>Gráficos guardados</h2></div></header>{charts.map(chart=><div className={styles.savedRow} key={chart.id}><span className={styles.savedIcon}><BarChart3 size={16}/></span><div><strong>{chart.title}</strong><small>{metricLabels[chart.metric]} por {dimensionLabels[chart.dimension].toLowerCase()} · {chart.chartType}</small></div><button onClick={()=>removeChart(chart.id)} disabled={busy} aria-label="Eliminar"><Trash2 size={15}/></button></div>)}</section></div>;
}
