"use client";
import { useState } from "react";
import { BarChart3, Plus, Trash2, X } from "lucide-react";
import AnalyticsChart from "@/components/ui/AnalyticsChart/AnalyticsChart";
import { useAnalytics } from "@/contexts/AnalyticsContext";
import { aggregate, dimensionLabels, metricLabels } from "@/lib/analytics";
import { useProgram } from "@/contexts/ProgramContext";
import type { ChartType, Dimension, Metric } from "@/types/analytics";
import styles from "./DashboardCharts.module.css";

export default function DashboardCharts(){
 const {charts,addChart,removeChart,busy,error}=useAnalytics(); const {analytics}=useProgram();const [open,setOpen]=useState(false);
 async function create(formData:FormData){const saved=await addChart({title:String(formData.get("title")),dimension:String(formData.get("dimension")) as Dimension,metric:String(formData.get("metric")) as Metric,chartType:String(formData.get("chartType")) as ChartType,state:String(formData.get("state"))});if(saved)setOpen(false);}
 return <section className={styles.section}>{error&&<p role="alert" className="operation-error">{error}</p>}<header className={styles.header}><div><span className="eyebrow">Analítica configurable</span><h2>Gráficos del Dashboard</h2></div><button className={`primary-btn ${styles.add}`} onClick={()=>setOpen(true)}><Plus size={15}/> Crear gráfico</button></header>{charts.length?<div className={styles.grid}>{charts.map(chart=><article className={`panel ${styles.chartCard}`} key={chart.id}><header className={styles.chartHead}><div><span className="eyebrow">{metricLabels[chart.metric]}</span><h3>{chart.title}</h3><small>Por {dimensionLabels[chart.dimension].toLowerCase()} · {chart.state}</small></div><button className={styles.remove} onClick={()=>removeChart(chart.id)} disabled={busy} aria-label="Quitar gráfico"><Trash2 size={14}/></button></header><AnalyticsChart data={aggregate(analytics,chart)} type={chart.chartType} metric={chart.metric}/></article>)}</div>:<div className={styles.empty}>No hay gráficos guardados. Creá uno para empezar.</div>}
 {open&&<div className={styles.overlay}><section className={styles.modal} role="dialog" aria-modal="true" aria-label="Crear gráfico"><header className={styles.modalHeader}><div><span className="eyebrow">Dashboard</span><h2>Crear gráfico</h2></div><button className={styles.close} onClick={()=>setOpen(false)}><X size={20}/></button></header><form onSubmit={event=>{event.preventDefault();void create(new FormData(event.currentTarget));}}><fieldset disabled={busy} className="form-fields"><div className={styles.form}>{error&&<p role="alert" className="operation-error">{error}</p>}<div className={`${styles.field} ${styles.wide}`}><label>Título</label><input name="title" maxLength={150} required defaultValue="Unidades por estado"/></div><div className={styles.field}><label>Agrupar por</label><select name="dimension" defaultValue="state">{Object.entries(dimensionLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div><div className={styles.field}><label>Métrica</label><select name="metric" defaultValue="units">{Object.entries(metricLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div><div className={styles.field}><label>Estado</label><select name="state" defaultValue="TODOS"><option value="TODOS">Todos</option><option>RETIRADO</option><option>STOCK</option><option>REPARTO</option><option>ENTREGADA</option></select></div><div className={styles.field}><label>Visualización</label><select name="chartType" defaultValue="bar"><option value="bar">Barras</option><option value="line">Línea</option><option value="donut">Dona</option></select></div></div><footer className={styles.actions}><button type="button" className={styles.cancel} onClick={()=>setOpen(false)}>Cancelar</button><button className={`primary-btn ${styles.save}`}><BarChart3 size={14}/> Agregar al Dashboard</button></footer></fieldset></form></section></div>}</section>;
}
