BEGIN;

ALTER TABLE public.unidad ADD COLUMN IF NOT EXISTS entrega_modo text DEFAULT 'RETIRA_CLIENTE';

WITH fallback AS (
 INSERT INTO public.repartidor(nombre,observaciones)
 VALUES('Historico sin registrar','Repartidor tecnico para pedidos anteriores a la trazabilidad completa.')
 ON CONFLICT(nombre) DO UPDATE SET observaciones=coalesce(public.repartidor.observaciones,excluded.observaciones)
 RETURNING id
)
UPDATE public.pedido
SET repartidor_id=(SELECT id FROM fallback)
WHERE estado<>'BORRADOR' AND repartidor_id IS NULL;

UPDATE public.unidad
SET entrega_modo=CASE WHEN repartidor_id IS NULL THEN 'RETIRA_CLIENTE' ELSE 'REPARTIDOR' END
WHERE estado IN ('REPARTO','ENTREGADA') AND entrega_modo IS NULL;

UPDATE public.unidad
SET repartidor_id=NULL
WHERE estado IN ('REPARTO','ENTREGADA') AND entrega_modo='RETIRA_CLIENTE' AND repartidor_id IS NOT NULL;

DO $$
BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='chk_pedido_repartidor_generado') THEN
  ALTER TABLE public.pedido ADD CONSTRAINT chk_pedido_repartidor_generado CHECK (estado='BORRADOR' OR repartidor_id IS NOT NULL);
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='chk_unidad_entrega_modo') THEN
  ALTER TABLE public.unidad ADD CONSTRAINT chk_unidad_entrega_modo CHECK (
   estado NOT IN ('REPARTO','ENTREGADA')
   OR (
    entrega_modo IN ('REPARTIDOR','RETIRA_CLIENTE')
    AND (entrega_modo<>'REPARTIDOR' OR repartidor_id IS NOT NULL)
    AND (entrega_modo<>'RETIRA_CLIENTE' OR repartidor_id IS NULL)
   )
  );
 END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.ruta_reparto (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 repartidor_id bigint NOT NULL REFERENCES public.repartidor(id) ON DELETE RESTRICT,
 fecha date NOT NULL,
 estado text NOT NULL DEFAULT 'EN_CURSO' CHECK (estado IN ('EN_CURSO','CERRADA')),
 dinero_entregado_usd numeric(14,2) NOT NULL DEFAULT 0 CHECK (dinero_entregado_usd>=0),
 dinero_devuelto_usd numeric(14,2) CHECK (dinero_devuelto_usd>=0),
 solicitud_id uuid UNIQUE,
 observaciones text,
 creado_en timestamptz NOT NULL DEFAULT now(),
 cerrada_en timestamptz
);

CREATE TABLE IF NOT EXISTS public.ruta_reparto_pedido (
 ruta_id bigint NOT NULL REFERENCES public.ruta_reparto(id) ON DELETE CASCADE,
 pedido_id bigint NOT NULL REFERENCES public.pedido(id) ON DELETE RESTRICT,
 PRIMARY KEY(ruta_id,pedido_id),
 UNIQUE(pedido_id)
);

CREATE TABLE IF NOT EXISTS public.ruta_reparto_unidad (
 ruta_id bigint NOT NULL REFERENCES public.ruta_reparto(id) ON DELETE CASCADE,
 unidad_id bigint NOT NULL REFERENCES public.unidad(id) ON DELETE RESTRICT,
 PRIMARY KEY(ruta_id,unidad_id),
 UNIQUE(unidad_id)
);

CREATE TABLE IF NOT EXISTS public.ruta_reparto_movimiento (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 ruta_id bigint NOT NULL REFERENCES public.ruta_reparto(id) ON DELETE CASCADE,
 tipo text NOT NULL CHECK (tipo IN ('ENTREGADO','PAGO_PROVEEDOR','COBRO_CLIENTE','DEVUELTO','AJUSTE')),
 importe_usd numeric(14,2) NOT NULL CHECK (importe_usd>=0),
 referencia_tipo text,
 referencia_id bigint,
 observaciones text,
 creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE SEQUENCE IF NOT EXISTS public.comprobante_venta_numero_seq;
CREATE TABLE IF NOT EXISTS public.comprobante_venta (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 unidad_id bigint NOT NULL UNIQUE REFERENCES public.unidad(id) ON DELETE RESTRICT,
 numero bigint NOT NULL DEFAULT nextval('public.comprobante_venta_numero_seq') UNIQUE,
 fecha timestamptz NOT NULL DEFAULT now(),
 cliente_nombre text NOT NULL,
 producto_nombre text NOT NULL,
 total_usd numeric(14,2) NOT NULL CHECK (total_usd>=0),
 pagado_usd numeric(14,2) NOT NULL CHECK (pagado_usd>=0),
 saldo_usd numeric(14,2) NOT NULL,
 estado text NOT NULL CHECK (estado IN ('REPARTO','ENTREGADA')),
 contenido jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_ruta_reparto_repartidor ON public.ruta_reparto(repartidor_id,fecha);
CREATE INDEX IF NOT EXISTS idx_ruta_movimiento_ruta ON public.ruta_reparto_movimiento(ruta_id,tipo);
CREATE INDEX IF NOT EXISTS idx_comprobante_unidad ON public.comprobante_venta(unidad_id);

ALTER TABLE public.ruta_reparto ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ruta_reparto_pedido ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ruta_reparto_unidad ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ruta_reparto_movimiento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comprobante_venta ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE t text;
BEGIN
 FOREACH t IN ARRAY ARRAY['ruta_reparto','ruta_reparto_pedido','ruta_reparto_unidad','ruta_reparto_movimiento','comprobante_venta'] LOOP
  EXECUTE format('GRANT SELECT ON public.%I TO anon',t);
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename=t AND policyname='app_read') THEN
   EXECUTE format('CREATE POLICY app_read ON public.%I FOR SELECT TO anon USING(true)',t);
  END IF;
 END LOOP;
END $$;

CREATE OR REPLACE FUNCTION public.pgl_assign_order_courier(p_id bigint,p_courier bigint) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE current_status text;
BEGIN
 SELECT estado INTO current_status FROM public.pedido WHERE id=p_id FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Pedido inexistente'; END IF;
 IF p_courier IS NULL AND current_status<>'BORRADOR' THEN RAISE EXCEPTION 'Los pedidos generados necesitan repartidor'; END IF;
 IF p_courier IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.repartidor WHERE id=p_courier) THEN
  RAISE EXCEPTION 'Selecciona un repartidor existente';
 END IF;
 UPDATE public.pedido SET repartidor_id=p_courier WHERE id=p_id;
END $$;

CREATE OR REPLACE FUNCTION public.pgl_generate_orders(p_ids jsonb) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE changed integer;
BEGIN
 IF jsonb_typeof(p_ids) IS DISTINCT FROM 'array' THEN RAISE EXCEPTION 'Selecciona pedidos validos'; END IF;
 IF EXISTS (
  SELECT 1 FROM public.pedido p
  WHERE p.estado='BORRADOR'
   AND p.id IN (SELECT value::bigint FROM jsonb_array_elements_text(p_ids))
   AND p.repartidor_id IS NULL
 ) THEN
  RAISE EXCEPTION 'Asigna un repartidor antes de generar pedidos';
 END IF;
 UPDATE public.pedido SET estado='PEDIDO'
 WHERE estado='BORRADOR' AND id IN (SELECT value::bigint FROM jsonb_array_elements_text(p_ids));
 GET DIAGNOSTICS changed = ROW_COUNT;
 RETURN changed;
END $$;

CREATE OR REPLACE FUNCTION public.pgl_set_sale_delivery(p_unit bigint,p_mode text,p_courier bigint) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE mode text:=upper(coalesce(nullif(trim(p_mode),''),'RETIRA_CLIENTE'));
BEGIN
 IF mode NOT IN ('REPARTIDOR','RETIRA_CLIENTE') THEN RAISE EXCEPTION 'Selecciona un modo de entrega valido'; END IF;
 IF mode='REPARTIDOR' THEN
  IF p_courier IS NULL OR NOT EXISTS(SELECT 1 FROM public.repartidor WHERE id=p_courier) THEN RAISE EXCEPTION 'Selecciona un repartidor existente'; END IF;
 ELSE
  IF p_courier IS NOT NULL THEN RAISE EXCEPTION 'El retiro del cliente no usa repartidor'; END IF;
 END IF;
 UPDATE public.unidad
 SET entrega_modo=mode,repartidor_id=CASE WHEN mode='REPARTIDOR' THEN p_courier ELSE NULL END
 WHERE id=p_unit AND estado IN ('REPARTO','ENTREGADA');
 IF NOT FOUND THEN RAISE EXCEPTION 'La unidad no tiene una venta activa'; END IF;
END $$;

CREATE OR REPLACE FUNCTION public.pgl_assign_sale_courier(p_unit bigint,p_courier bigint) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 PERFORM public.pgl_set_sale_delivery(p_unit,CASE WHEN p_courier IS NULL THEN 'RETIRA_CLIENTE' ELSE 'REPARTIDOR' END,p_courier);
END $$;

CREATE OR REPLACE FUNCTION public.pgl_add_sale_payment(p_id bigint,p_amount numeric,p_request uuid,p_delivered boolean)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE item public.unidad%rowtype; previous public.venta_abono%rowtype; paid numeric; result bigint; active_route bigint;
BEGIN
 IF p_request IS NULL THEN RAISE EXCEPTION 'Falta el identificador del abono'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(p_request::text,0));
 SELECT * INTO item FROM public.unidad WHERE id=p_id FOR UPDATE;
 IF NOT FOUND OR item.fecha_venta IS NULL THEN RAISE EXCEPTION 'No hay una venta para esta unidad'; END IF;
 SELECT * INTO previous FROM public.venta_abono WHERE solicitud_id=p_request;
 IF FOUND THEN
  IF previous.unidad_id <> p_id OR previous.importe_usd IS DISTINCT FROM p_amount THEN RAISE EXCEPTION 'El reintento no coincide con el abono original'; END IF;
  RETURN previous.id;
 END IF;
 IF p_amount IS NULL OR p_amount::text IN ('NaN','Infinity','-Infinity') OR p_amount<=0 OR p_amount<>round(p_amount,2) THEN RAISE EXCEPTION 'Ingresa un importe positivo con hasta dos decimales'; END IF;
 IF item.estado NOT IN ('REPARTO','ENTREGADA') THEN RAISE EXCEPTION 'La venta no admite abonos'; END IF;
 SELECT item.cobrado_inicial_usd + coalesce(sum(importe_usd),0) INTO paid FROM public.venta_abono WHERE unidad_id=p_id;
 IF paid+p_amount > item.precio_venta_usd THEN RAISE EXCEPTION 'El abono supera el saldo pendiente. Actualiza la venta'; END IF;
 IF paid+p_amount=item.precio_venta_usd AND item.estado<>'ENTREGADA' AND p_delivered IS DISTINCT FROM true THEN RAISE EXCEPTION 'Confirma el retiro para completar el pago'; END IF;
 INSERT INTO public.venta_abono(unidad_id,importe_usd,solicitud_id) VALUES(p_id,p_amount,p_request) RETURNING id INTO result;
 UPDATE public.unidad SET pago_verificado=(paid+p_amount=precio_venta_usd),
 estado=CASE WHEN p_delivered THEN 'ENTREGADA' ELSE estado END,
 fecha_entrega=CASE WHEN p_delivered THEN coalesce(fecha_entrega,now()) ELSE fecha_entrega END WHERE id=p_id;
 SELECT ru.ruta_id INTO active_route
 FROM public.ruta_reparto_unidad ru
 JOIN public.ruta_reparto r ON r.id=ru.ruta_id
 WHERE ru.unidad_id=p_id AND r.estado='EN_CURSO'
 ORDER BY r.id DESC LIMIT 1;
 IF active_route IS NOT NULL THEN
  INSERT INTO public.ruta_reparto_movimiento(ruta_id,tipo,importe_usd,referencia_tipo,referencia_id)
  VALUES(active_route,'COBRO_CLIENTE',p_amount,'venta_abono',result);
 END IF;
 PERFORM public.pgl_generate_sale_receipt(p_id);
 RETURN result;
END $$;

CREATE OR REPLACE FUNCTION public.pgl_create_sale_with_delivery(p_unit bigint,p_client bigint,p_seller bigint,p_date date,p_price numeric,p_commission numeric,p_amount numeric,p_request uuid,p_delivered boolean,p_delivery_mode text,p_courier bigint)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE result bigint; existing public.unidad%rowtype; mode text:=upper(coalesce(nullif(trim(p_delivery_mode),''),'RETIRA_CLIENTE'));
BEGIN
 IF mode NOT IN ('REPARTIDOR','RETIRA_CLIENTE') THEN RAISE EXCEPTION 'Selecciona un modo de entrega valido'; END IF;
 IF mode='REPARTIDOR' AND (p_courier IS NULL OR NOT EXISTS(SELECT 1 FROM public.repartidor WHERE id=p_courier)) THEN RAISE EXCEPTION 'Selecciona un repartidor existente'; END IF;
 IF mode='RETIRA_CLIENTE' AND p_courier IS NOT NULL THEN RAISE EXCEPTION 'El retiro del cliente no usa repartidor'; END IF;
 SELECT * INTO existing FROM public.unidad WHERE id=p_unit FOR UPDATE;
 IF existing.solicitud_venta_id=p_request THEN
  IF existing.entrega_modo IS DISTINCT FROM mode OR existing.repartidor_id IS DISTINCT FROM (CASE WHEN mode='REPARTIDOR' THEN p_courier ELSE NULL END) THEN
   RAISE EXCEPTION 'El reintento no coincide con la entrega original';
  END IF;
 END IF;
 result:=public.pgl_create_sale_partial(p_unit,p_client,p_seller,p_date,p_price,p_commission,p_amount,p_request,p_delivered);
 PERFORM public.pgl_set_sale_delivery(result,mode,CASE WHEN mode='REPARTIDOR' THEN p_courier ELSE NULL END);
 PERFORM public.pgl_generate_sale_receipt(result);
 RETURN result;
END $$;

CREATE OR REPLACE FUNCTION public.pgl_receive_and_pay_order(p_id bigint,p_units jsonb,p_amount numeric) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE purchase public.pedido%ROWTYPE; detail public.detalle_pedido%ROWTYPE; accepted integer; total numeric:=0; unit_count integer; shipping_cents bigint; item_index integer; inserted_count integer:=0; payment_id bigint; active_route bigint;
BEGIN
 SELECT * INTO purchase FROM public.pedido WHERE id=p_id FOR UPDATE;
 IF NOT FOUND OR purchase.estado NOT IN ('PEDIDO',U&'ENV\00CDO') THEN RAISE EXCEPTION 'El pedido no esta pendiente de recepcion'; END IF;
 IF jsonb_typeof(p_units) IS DISTINCT FROM 'array' OR jsonb_array_length(p_units)=0 THEN RAISE EXCEPTION 'Selecciona al menos una unidad recibida'; END IF;
 IF EXISTS (SELECT 1 FROM jsonb_array_elements(p_units) AS received(value) WHERE NOT EXISTS (SELECT 1 FROM public.detalle_pedido d WHERE d.pedido_id=p_id AND d.id=(received.value->>'detalle_id')::bigint)) THEN RAISE EXCEPTION 'Hay unidades sin una linea valida'; END IF;
 unit_count:=jsonb_array_length(p_units); shipping_cents:=round(purchase.costo_envio_usd*100);
 FOR detail IN SELECT * FROM public.detalle_pedido WHERE pedido_id=p_id ORDER BY id LOOP
  SELECT count(*) INTO accepted FROM jsonb_array_elements(p_units) AS received(value) WHERE (received.value->>'detalle_id')::bigint=detail.id;
  IF accepted>detail.cantidad THEN RAISE EXCEPTION 'La cantidad recibida no es valida'; END IF;
  FOR item_index IN 1..accepted LOOP
   inserted_count:=inserted_count+1;
   INSERT INTO public.unidad(pedido_id,detalle_pedido_id,producto_id,estado,color,codigo,precio_costo_usd,costo_envio_usd,fecha_retiro,fecha_ingreso_stock)
   VALUES(p_id,detail.id,detail.producto_id,'STOCK',detail.color,NULL,detail.precio_costo_usd,((shipping_cents/unit_count)+CASE WHEN inserted_count<=shipping_cents%unit_count THEN 1 ELSE 0 END)::numeric/100,now(),now());
  END LOOP;
  total:=total+(accepted*detail.precio_costo_usd);
  IF accepted=0 THEN DELETE FROM public.detalle_pedido WHERE id=detail.id;
  ELSE UPDATE public.detalle_pedido SET cantidad=accepted WHERE id=detail.id;
  END IF;
 END LOOP;
 total:=total+purchase.costo_envio_usd;
 IF p_amount IS NULL OR p_amount<0 OR p_amount>total THEN RAISE EXCEPTION 'El importe abonado no puede superar el total'; END IF;
 INSERT INTO public.proveedor_pago(pedido_id,proveedor_id,importe_usd) VALUES(p_id,purchase.proveedor_id,p_amount) RETURNING id INTO payment_id;
 UPDATE public.pedido SET estado='RECIBIDO' WHERE id=p_id;
 SELECT rp.ruta_id INTO active_route
 FROM public.ruta_reparto_pedido rp
 JOIN public.ruta_reparto r ON r.id=rp.ruta_id
 WHERE rp.pedido_id=p_id AND r.estado='EN_CURSO'
 ORDER BY r.id DESC LIMIT 1;
 IF active_route IS NOT NULL AND p_amount>0 THEN
  INSERT INTO public.ruta_reparto_movimiento(ruta_id,tipo,importe_usd,referencia_tipo,referencia_id)
  VALUES(active_route,'PAGO_PROVEEDOR',p_amount,'proveedor_pago',payment_id);
 END IF;
END $$;

CREATE OR REPLACE FUNCTION public.pgl_create_delivery_route(p_courier bigint,p_date date,p_cash numeric,p_order_ids jsonb,p_unit_ids jsonb,p_request uuid)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE result bigint; order_count integer; unit_count integer;
BEGIN
 IF p_request IS NULL THEN RAISE EXCEPTION 'Falta el identificador de la ruta'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(p_request::text,0));
 SELECT id INTO result FROM public.ruta_reparto WHERE solicitud_id=p_request;
 IF FOUND THEN RETURN result; END IF;
 IF p_courier IS NULL OR NOT EXISTS(SELECT 1 FROM public.repartidor WHERE id=p_courier) THEN RAISE EXCEPTION 'Selecciona un repartidor existente'; END IF;
 IF p_date IS NULL THEN RAISE EXCEPTION 'Selecciona la fecha de la ruta'; END IF;
 IF p_cash IS NULL OR p_cash<0 OR p_cash<>round(p_cash,2) THEN RAISE EXCEPTION 'Revisa el dinero entregado'; END IF;
 IF coalesce(jsonb_typeof(p_order_ids),'array')<>'array' OR coalesce(jsonb_typeof(p_unit_ids),'array')<>'array' THEN RAISE EXCEPTION 'Selecciona pedidos y ventas validas'; END IF;
 SELECT count(DISTINCT value::bigint) INTO order_count FROM jsonb_array_elements_text(coalesce(p_order_ids,'[]'::jsonb));
 SELECT count(DISTINCT value::bigint) INTO unit_count FROM jsonb_array_elements_text(coalesce(p_unit_ids,'[]'::jsonb));
 IF order_count+unit_count=0 THEN RAISE EXCEPTION 'La ruta necesita al menos un pedido o una venta'; END IF;
 IF EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(p_order_ids,'[]'::jsonb)) ids(value) JOIN public.pedido p ON p.id=ids.value::bigint WHERE p.estado NOT IN ('PEDIDO',U&'ENV\00CDO')) THEN
  RAISE EXCEPTION 'La ruta solo admite pedidos generados pendientes';
 END IF;
 IF EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(p_unit_ids,'[]'::jsonb)) ids(value) JOIN public.unidad u ON u.id=ids.value::bigint WHERE u.estado<>'REPARTO') THEN
  RAISE EXCEPTION 'La ruta solo admite ventas en reparto';
 END IF;
 IF EXISTS (SELECT 1 FROM public.ruta_reparto_pedido rp WHERE rp.pedido_id IN (SELECT value::bigint FROM jsonb_array_elements_text(coalesce(p_order_ids,'[]'::jsonb)))) THEN
  RAISE EXCEPTION 'Hay pedidos que ya pertenecen a una ruta';
 END IF;
 IF EXISTS (SELECT 1 FROM public.ruta_reparto_unidad ru WHERE ru.unidad_id IN (SELECT value::bigint FROM jsonb_array_elements_text(coalesce(p_unit_ids,'[]'::jsonb)))) THEN
  RAISE EXCEPTION 'Hay ventas que ya pertenecen a una ruta';
 END IF;
 INSERT INTO public.ruta_reparto(repartidor_id,fecha,dinero_entregado_usd,solicitud_id)
 VALUES(p_courier,p_date,p_cash,p_request) RETURNING id INTO result;
 INSERT INTO public.ruta_reparto_pedido(ruta_id,pedido_id)
 SELECT result,value::bigint FROM jsonb_array_elements_text(coalesce(p_order_ids,'[]'::jsonb)) GROUP BY value;
 INSERT INTO public.ruta_reparto_unidad(ruta_id,unidad_id)
 SELECT result,value::bigint FROM jsonb_array_elements_text(coalesce(p_unit_ids,'[]'::jsonb)) GROUP BY value;
 UPDATE public.pedido SET repartidor_id=p_courier WHERE id IN (SELECT value::bigint FROM jsonb_array_elements_text(coalesce(p_order_ids,'[]'::jsonb)));
 UPDATE public.unidad SET entrega_modo='REPARTIDOR',repartidor_id=p_courier WHERE id IN (SELECT value::bigint FROM jsonb_array_elements_text(coalesce(p_unit_ids,'[]'::jsonb)));
 IF p_cash>0 THEN
  INSERT INTO public.ruta_reparto_movimiento(ruta_id,tipo,importe_usd,observaciones) VALUES(result,'ENTREGADO',p_cash,'Dinero entregado al repartidor');
 END IF;
 RETURN result;
END $$;

CREATE OR REPLACE FUNCTION public.pgl_close_delivery_route(p_id bigint,p_returned numeric,p_notes text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE route public.ruta_reparto%rowtype; paid_suppliers numeric; collected_clients numeric; expected numeric; difference numeric;
BEGIN
 SELECT * INTO route FROM public.ruta_reparto WHERE id=p_id FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Ruta inexistente'; END IF;
 IF route.estado='CERRADA' THEN
  RETURN jsonb_build_object('expected',0,'returned',route.dinero_devuelto_usd,'difference',0);
 END IF;
 IF p_returned IS NULL OR p_returned<0 OR p_returned<>round(p_returned,2) THEN RAISE EXCEPTION 'Revisa el dinero devuelto'; END IF;
 SELECT coalesce(sum(importe_usd),0) INTO paid_suppliers FROM public.ruta_reparto_movimiento WHERE ruta_id=p_id AND tipo='PAGO_PROVEEDOR';
 SELECT coalesce(sum(importe_usd),0) INTO collected_clients FROM public.ruta_reparto_movimiento WHERE ruta_id=p_id AND tipo='COBRO_CLIENTE';
 expected:=route.dinero_entregado_usd-paid_suppliers+collected_clients;
 difference:=p_returned-expected;
 UPDATE public.ruta_reparto SET estado='CERRADA',dinero_devuelto_usd=p_returned,observaciones=nullif(trim(coalesce(p_notes,'')),''),cerrada_en=now() WHERE id=p_id;
 INSERT INTO public.ruta_reparto_movimiento(ruta_id,tipo,importe_usd,observaciones) VALUES(p_id,'DEVUELTO',p_returned,'Rendicion de ruta');
 RETURN jsonb_build_object('expected',expected,'returned',p_returned,'difference',difference,'supplierPaid',paid_suppliers,'clientCollected',collected_clients);
END $$;

CREATE OR REPLACE FUNCTION public.pgl_generate_sale_receipt(p_unit bigint) RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE item public.unidad%rowtype; client_name text; product_name text; paid numeric; receipt_id bigint;
BEGIN
 SELECT * INTO item FROM public.unidad WHERE id=p_unit;
 IF NOT FOUND OR item.estado NOT IN ('REPARTO','ENTREGADA') OR item.fecha_venta IS NULL THEN RAISE EXCEPTION 'La unidad no tiene una venta activa'; END IF;
 SELECT nombre INTO client_name FROM public.cliente WHERE id=item.cliente_id;
 SELECT concat_ws(' ',nullif(trim(marca),''),nombre) INTO product_name FROM public.producto WHERE id=item.producto_id;
 SELECT item.cobrado_inicial_usd+coalesce(sum(importe_usd),0) INTO paid FROM public.venta_abono WHERE unidad_id=p_unit;
 INSERT INTO public.comprobante_venta(unidad_id,cliente_nombre,producto_nombre,total_usd,pagado_usd,saldo_usd,estado,contenido)
 VALUES(p_unit,coalesce(client_name,'Cliente no disponible'),coalesce(product_name,'Producto no disponible'),coalesce(item.precio_venta_usd,0),paid,coalesce(item.precio_venta_usd,0)-paid,item.estado,
  jsonb_build_object('unidadId',p_unit,'clienteId',item.cliente_id,'vendedorId',item.vendedor_id,'repartidorId',item.repartidor_id,'modoEntrega',item.entrega_modo,'fechaVenta',item.fecha_venta,'fechaEntrega',item.fecha_entrega))
 ON CONFLICT(unidad_id) DO UPDATE SET
  fecha=now(),
  cliente_nombre=excluded.cliente_nombre,
  producto_nombre=excluded.producto_nombre,
  total_usd=excluded.total_usd,
  pagado_usd=excluded.pagado_usd,
  saldo_usd=excluded.saldo_usd,
  estado=excluded.estado,
  contenido=excluded.contenido
 RETURNING id INTO receipt_id;
 RETURN receipt_id;
END $$;

CREATE OR REPLACE FUNCTION public.pgl_snapshot() RETURNS jsonb LANGUAGE sql STABLE SECURITY INVOKER SET search_path='' AS $$
 SELECT public.pgl_snapshot_alpha() || jsonb_build_object(
  'salePayments',coalesce((SELECT jsonb_agg(t ORDER BY registrado_en,id) FROM public.venta_abono t),'[]'::jsonb),
  'categories',coalesce((SELECT jsonb_agg(t ORDER BY nombre,id) FROM public.categorias t),'[]'::jsonb),
  'categoryCharacteristics',coalesce((SELECT jsonb_agg(t ORDER BY categoria_id,id) FROM public.categoria_caracteristica t),'[]'::jsonb),
  'supplierPayments',coalesce((SELECT jsonb_agg(t ORDER BY registrado_en,id) FROM public.proveedor_pago t),'[]'::jsonb),
  'couriers',coalesce((SELECT jsonb_agg(t ORDER BY id DESC) FROM public.repartidor t),'[]'::jsonb),
  'routes',coalesce((SELECT jsonb_agg(t ORDER BY fecha DESC,id DESC) FROM public.ruta_reparto t),'[]'::jsonb),
  'routeOrders',coalesce((SELECT jsonb_agg(t ORDER BY ruta_id,pedido_id) FROM public.ruta_reparto_pedido t),'[]'::jsonb),
  'routeUnits',coalesce((SELECT jsonb_agg(t ORDER BY ruta_id,unidad_id) FROM public.ruta_reparto_unidad t),'[]'::jsonb),
  'routeMovements',coalesce((SELECT jsonb_agg(t ORDER BY creado_en,id) FROM public.ruta_reparto_movimiento t),'[]'::jsonb),
  'receipts',coalesce((SELECT jsonb_agg(t ORDER BY fecha DESC,id DESC) FROM public.comprobante_venta t),'[]'::jsonb));
$$;

REVOKE ALL ON FUNCTION public.pgl_assign_order_courier(bigint,bigint),public.pgl_generate_orders(jsonb),public.pgl_set_sale_delivery(bigint,text,bigint),public.pgl_assign_sale_courier(bigint,bigint),public.pgl_add_sale_payment(bigint,numeric,uuid,boolean),public.pgl_create_sale_with_delivery(bigint,bigint,bigint,date,numeric,numeric,numeric,uuid,boolean,text,bigint),public.pgl_receive_and_pay_order(bigint,jsonb,numeric),public.pgl_create_delivery_route(bigint,date,numeric,jsonb,jsonb,uuid),public.pgl_close_delivery_route(bigint,numeric,text),public.pgl_generate_sale_receipt(bigint),public.pgl_snapshot() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.pgl_assign_order_courier(bigint,bigint),public.pgl_generate_orders(jsonb),public.pgl_set_sale_delivery(bigint,text,bigint),public.pgl_assign_sale_courier(bigint,bigint),public.pgl_add_sale_payment(bigint,numeric,uuid,boolean),public.pgl_create_sale_with_delivery(bigint,bigint,bigint,date,numeric,numeric,numeric,uuid,boolean,text,bigint),public.pgl_receive_and_pay_order(bigint,jsonb,numeric),public.pgl_create_delivery_route(bigint,date,numeric,jsonb,jsonb,uuid),public.pgl_close_delivery_route(bigint,numeric,text),public.pgl_generate_sale_receipt(bigint),public.pgl_snapshot() TO anon;
NOTIFY pgrst,'reload schema';

COMMIT;
