BEGIN;
CREATE TABLE public.proveedor_pago (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 pedido_id bigint NOT NULL REFERENCES public.pedido(id),
 proveedor_id bigint NOT NULL REFERENCES public.proveedor(id),
 importe_usd numeric(14,2) NOT NULL CHECK (importe_usd >= 0),
 registrado_en timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.proveedor_pago ENABLE ROW LEVEL SECURITY;
CREATE POLICY proveedor_pago_read ON public.proveedor_pago FOR SELECT TO anon USING (true);
GRANT SELECT ON public.proveedor_pago TO anon;

CREATE FUNCTION public.pgl_generate_orders(p_ids jsonb) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE changed integer;
BEGIN
 UPDATE public.pedido SET estado='PEDIDO' WHERE estado='BORRADOR' AND id IN (SELECT value::bigint FROM jsonb_array_elements_text(p_ids));
 GET DIAGNOSTICS changed = ROW_COUNT; RETURN changed;
END $$;

CREATE FUNCTION public.pgl_receive_and_pay_order(p_id bigint,p_units jsonb,p_amount numeric) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE purchase public.pedido%ROWTYPE; item jsonb; detail public.detalle_pedido%ROWTYPE; accepted integer; total numeric:=0;
BEGIN
 SELECT * INTO purchase FROM public.pedido WHERE id=p_id FOR UPDATE;
 IF purchase.id IS NULL OR purchase.estado NOT IN ('PEDIDO','ENVÍO') THEN RAISE EXCEPTION 'El pedido no está pendiente de recepción'; END IF;
 IF jsonb_typeof(p_units) IS DISTINCT FROM 'array' OR jsonb_array_length(p_units)=0 THEN RAISE EXCEPTION 'Seleccioná al menos una unidad recibida'; END IF;
 IF EXISTS (SELECT 1 FROM jsonb_array_elements(p_units) u WHERE NOT EXISTS (SELECT 1 FROM public.detalle_pedido d WHERE d.pedido_id=p_id AND d.id=(u->>'detalle_id')::bigint)) THEN RAISE EXCEPTION 'Hay unidades sin una línea válida'; END IF;
 FOR detail IN SELECT * FROM public.detalle_pedido WHERE pedido_id=p_id LOOP
  SELECT count(*) INTO accepted FROM jsonb_array_elements(p_units) item WHERE (item->>'detalle_id')::bigint=detail.id;
  IF accepted>detail.cantidad THEN RAISE EXCEPTION 'La cantidad recibida no es válida'; END IF;
  IF accepted>0 THEN
   FOR item IN SELECT value FROM jsonb_array_elements(p_units) WHERE (value->>'detalle_id')::bigint=detail.id LOOP
    INSERT INTO public.unidad(producto_id,pedido_id,detalle_pedido_id,color,estado,fecha_retiro,precio_costo_usd,costo_envio_usd)
    VALUES(detail.producto_id,p_id,detail.id,detail.color,'STOCK',current_date,detail.precio_costo_usd,0);
   END LOOP;
   total:=total+(accepted*detail.precio_costo_usd);
  END IF;
  UPDATE public.detalle_pedido SET cantidad=accepted WHERE id=detail.id;
 END LOOP;
 total:=total+purchase.costo_envio_usd;
 IF p_amount<0 OR p_amount>total THEN RAISE EXCEPTION 'El importe abonado no puede superar el total'; END IF;
 INSERT INTO public.proveedor_pago(pedido_id,proveedor_id,importe_usd) VALUES(p_id,purchase.proveedor_id,p_amount);
 UPDATE public.pedido SET estado='RECIBIDO' WHERE id=p_id;
END $$;

CREATE OR REPLACE FUNCTION public.pgl_snapshot() RETURNS jsonb LANGUAGE sql STABLE SECURITY INVOKER SET search_path='' AS $$
 SELECT public.pgl_snapshot_alpha() || jsonb_build_object(
  'salePayments',coalesce((SELECT jsonb_agg(t ORDER BY registrado_en,id) FROM public.venta_abono t),'[]'::jsonb),
  'categories',coalesce((SELECT jsonb_agg(t ORDER BY nombre,id) FROM public.categorias t),'[]'::jsonb),
  'categoryCharacteristics',coalesce((SELECT jsonb_agg(t ORDER BY categoria_id,id) FROM public.categoria_caracteristica t),'[]'::jsonb),
  'supplierPayments',coalesce((SELECT jsonb_agg(t ORDER BY registrado_en,id) FROM public.proveedor_pago t),'[]'::jsonb));
$$;
REVOKE ALL ON FUNCTION public.pgl_generate_orders(jsonb),public.pgl_receive_and_pay_order(bigint,jsonb,numeric) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.pgl_generate_orders(jsonb),public.pgl_receive_and_pay_order(bigint,jsonb,numeric) TO anon;
NOTIFY pgrst,'reload schema';
COMMIT;
