-- ==========================================================
-- PGL Pulse
-- Base de Datos Oficial
-- Versión: 1.0
--
-- Proyecto:
-- Sistema de gestión para PGL Electrónica
--
-- Arquitectura:
-- ACU (Arquitectura Centrada en la Unidad)
--
-- Motor:
-- PostgreSQL (Supabase)
--
-- Este archivo crea toda la estructura de la base de datos.
-- ==========================================================

-- CONVENCIONES
--
-- • Todas las tablas se nombran en singular.
-- • Clave primaria: id.
-- • Claves foráneas: <tabla>_id.
-- • Importes: NUMERIC(10,2).
-- • Fechas completas: TIMESTAMPTZ.
-- • Horarios: TIME.
-- • Nunca se eliminan registros relacionados.
-- • Todas las FK utilizan ON DELETE RESTRICT.

-- ==========================================================
-- TABLAS
-- ==========================================================

-- ==========================================================
--TABLA PROVEEDOR

CREATE TABLE proveedor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    contacto VARCHAR(120),
    telefono VARCHAR(50),
    direccion TEXT,
    horario_desde TIME,
    horario_hasta TIME,
    observaciones TEXT
);

-- ==========================================================
--TABLA CLIENTE

CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    telefono VARCHAR(50),
    direccion TEXT,
    localidad VARCHAR(120),
    observaciones TEXT
);

-- ==========================================================
--TABLA VENDEDOR

CREATE TABLE vendedor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    telefono VARCHAR(50),
    porcentaje_comision NUMERIC(5,2) NOT NULL,
    observaciones TEXT
);

-- ==========================================================
--TABLA PRODUCTO

CREATE TABLE producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca VARCHAR(80) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    categoria VARCHAR(80) NOT NULL
);

-- ==========================================================
--TABLA PEDIDO

CREATE TABLE pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id BIGINT NOT NULL,
    fecha_pedido TIMESTAMPTZ,
    costo_envio_usd NUMERIC(10,2) NOT NULL,
    observaciones TEXT
);

-- ==========================================================
--TABLA DETALLE_PEDIDO

CREATE TABLE detalle_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    color VARCHAR(60) NOT NULL,
    cantidad INTEGER NOT NULL
);

-- ==========================================================
--TABLA UNIDAD

CREATE TABLE unidad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    cliente_id BIGINT,
    vendedor_id BIGINT,
    estado VARCHAR(20) NOT NULL,
    color VARCHAR(60) NOT NULL,
    codigo VARCHAR(120),
    precio_costo_usd NUMERIC(10,2) NOT NULL,
    costo_envio_usd NUMERIC(10,2) NOT NULL,
    precio_venta_usd NUMERIC(10,2),
    comision_usd NUMERIC(10,2),
    pago_verificado BOOLEAN NOT NULL DEFAULT FALSE,
    garantia BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_garantia TIMESTAMPTZ,
    fecha_retiro TIMESTAMPTZ NOT NULL,
    fecha_entrega TIMESTAMPTZ,
    observaciones TEXT
);

-- ==========================================================
-- FOREIGN KEYS
-- ==========================================================

-- ----------------------------------------------------------
-- pedido → proveedor
--
-- Un pedido siempre pertenece a un proveedor.
-- No se permite eliminar un proveedor que tenga pedidos.
-- ----------------------------------------------------------

ALTER TABLE pedido
ADD CONSTRAINT fk_pedido_proveedor
FOREIGN KEY (proveedor_id)
REFERENCES proveedor(id)
ON DELETE RESTRICT;

-- ----------------------------------------------------------
-- detalle_pedido → pedido
--
-- Cada detalle pertenece a un único pedido.
-- No se permite eliminar un pedido con detalles asociados.
-- ----------------------------------------------------------

ALTER TABLE detalle_pedido
ADD CONSTRAINT fk_detalle_pedido_pedido
FOREIGN KEY (pedido_id)
REFERENCES pedido(id)
ON DELETE RESTRICT;

-- ----------------------------------------------------------
-- detalle_pedido → producto
--
-- Cada detalle hace referencia a un producto.
-- No se permite eliminar un producto utilizado en pedidos.
-- ----------------------------------------------------------

ALTER TABLE detalle_pedido
ADD CONSTRAINT fk_detalle_pedido_producto
FOREIGN KEY (producto_id)
REFERENCES producto(id)
ON DELETE RESTRICT;

-- ----------------------------------------------------------
-- unidad → pedido
--
-- Toda unidad nace a partir de un pedido.
-- No se permite eliminar un pedido que haya generado unidades.
-- ----------------------------------------------------------

ALTER TABLE unidad
ADD CONSTRAINT fk_unidad_pedido
FOREIGN KEY (pedido_id)
REFERENCES pedido(id)
ON DELETE RESTRICT;

-- ----------------------------------------------------------
-- unidad → producto
--
-- Cada unidad pertenece a un producto.
-- No se permite eliminar un producto con unidades asociadas.
-- ----------------------------------------------------------

ALTER TABLE unidad
ADD CONSTRAINT fk_unidad_producto
FOREIGN KEY (producto_id)
REFERENCES producto(id)
ON DELETE RESTRICT;

-- ----------------------------------------------------------
-- unidad → cliente
--
-- Una unidad puede estar asociada a un cliente.
-- El cliente es opcional hasta concretar la venta.
-- No se permite eliminar un cliente con unidades asociadas.
-- ----------------------------------------------------------

ALTER TABLE unidad
ADD CONSTRAINT fk_unidad_cliente
FOREIGN KEY (cliente_id)
REFERENCES cliente(id)
ON DELETE RESTRICT;

-- ----------------------------------------------------------
-- unidad → vendedor
--
-- Una unidad puede estar asociada a un vendedor.
-- El vendedor es opcional hasta registrar la venta.
-- No se permite eliminar un vendedor con unidades asociadas.
-- ----------------------------------------------------------

ALTER TABLE unidad
ADD CONSTRAINT fk_unidad_vendedor
FOREIGN KEY (vendedor_id)
REFERENCES vendedor(id)
ON DELETE RESTRICT;

-- ==========================================================
-- RESTRICCIONES
-- ==========================================================

-- ----------------------------------------------------------
-- producto
-- Evita productos duplicados de la misma marca.
-- ----------------------------------------------------------

ALTER TABLE producto
ADD CONSTRAINT uq_producto_marca_nombre
UNIQUE (marca, nombre);

-- ----------------------------------------------------------
-- detalle_pedido
-- La cantidad siempre debe ser mayor a cero.
-- ----------------------------------------------------------

ALTER TABLE detalle_pedido
ADD CONSTRAINT chk_detalle_pedido_cantidad
CHECK (cantidad > 0);

-- ----------------------------------------------------------
-- detalle_pedido
-- Evita productos reptidos dentro del mismo pedido.
-- ----------------------------------------------------------

ALTER TABLE detalle_pedido
ADD CONSTRAINT uq_detalle_pedido
UNIQUE (
    pedido_id,
    producto_id,
    color
);

-- ----------------------------------------------------------
-- pedido
-- El costo de envío nunca puede ser negativo.
-- ----------------------------------------------------------

ALTER TABLE pedido
ADD CONSTRAINT chk_pedido_costo_envio
CHECK (costo_envio_usd >= 0);

-- ----------------------------------------------------------
-- vendedor
-- La comisión nunca puede ser negativa.
-- ----------------------------------------------------------

ALTER TABLE vendedor
ADD CONSTRAINT chk_vendedor_porcentaje_comision
CHECK (porcentaje_comision >= 0);

-- ----------------------------------------------------------
-- unidad
-- El precio de costo nunca puede ser negativo.
-- ----------------------------------------------------------

ALTER TABLE unidad
ADD CONSTRAINT chk_unidad_precio_costo
CHECK (precio_costo_usd >= 0);

-- ----------------------------------------------------------
-- unidad
-- El costo de envío nunca puede ser negativo.
-- ----------------------------------------------------------

ALTER TABLE unidad
ADD CONSTRAINT chk_unidad_costo_envio
CHECK (costo_envio_usd >= 0);

-- ----------------------------------------------------------
-- unidad
-- El precio de venta nunca puede ser negativo.
-- Puede permanecer NULL mientras no exista venta.
-- ----------------------------------------------------------

ALTER TABLE unidad
ADD CONSTRAINT chk_unidad_precio_venta
CHECK (
    precio_venta_usd IS NULL
    OR precio_venta_usd >= 0
);

-- ----------------------------------------------------------
-- unidad
-- La comisión nunca puede ser negativa.
-- Puede permanecer NULL mientras no exista venta.
-- ----------------------------------------------------------

ALTER TABLE unidad
ADD CONSTRAINT chk_unidad_comision
CHECK (
    comision_usd IS NULL
    OR comision_usd >= 0
);

-- ----------------------------------------------------------
-- unidad
-- Estados permitidos por la ACU.
-- ----------------------------------------------------------

ALTER TABLE unidad
ADD CONSTRAINT chk_unidad_estado
CHECK (
    estado IN (
        'RETIRADO',
        'STOCK',
        'REPARTO',
        'ENTREGADA'
    )
);

-- ----------------------------------------------------------
-- unidad
-- Coherencia de garantía.
-- ----------------------------------------------------------

ALTER TABLE unidad
ADD CONSTRAINT chk_unidad_garantia
CHECK (
    (garantia = FALSE AND fecha_garantia IS NULL)
    OR
    (garantia = TRUE AND fecha_garantia IS NOT NULL)
);

-- ----------------------------------------------------------
-- unidad
-- La fecha de entrega solo existe cuando la unidad
-- fue entregada al cliente.
-- ----------------------------------------------------------

ALTER TABLE unidad
ADD CONSTRAINT chk_unidad_fecha_entrega
CHECK (
    (estado IN ('RETIRADO', 'STOCK', 'REPARTO') AND fecha_entrega IS NULL)
    OR
    (estado = 'ENTREGADA' AND fecha_entrega IS NOT NULL)
);

-- ----------------------------------------------------------
-- unidad
-- Cliente y vendedor solo pueden existir cuando
-- la unidad fue entregada.
-- ----------------------------------------------------------

ALTER TABLE unidad
ADD CONSTRAINT chk_unidad_cliente_vendedor
CHECK (
    (
        estado IN ('RETIRADO', 'STOCK')
        AND cliente_id IS NULL
        AND vendedor_id IS NULL
    )
    OR
    (
        estado IN ('REPARTO', 'ENTREGADA')
        AND cliente_id IS NOT NULL
        AND vendedor_id IS NOT NULL
    )
);

-- ----------------------------------------------------------
-- unidad
-- El pago solo puede verificarse cuando la unidad fue entregada.
-- ----------------------------------------------------------

ALTER TABLE unidad
ADD CONSTRAINT chk_unidad_pago_verificado
CHECK (
    (
        estado IN ('RETIRADO', 'STOCK')
        AND pago_verificado = FALSE
    )
    OR
    (
        estado IN ('REPARTO', 'ENTREGADA')
    )
);

-- ==========================================================
-- ÍNDICES
-- ==========================================================

-- ----------------------------------------------------------
-- pedido
-- Búsquedas por proveedor.
-- ----------------------------------------------------------

CREATE INDEX idx_pedido_proveedor
ON pedido (proveedor_id);

-- ----------------------------------------------------------
-- pedido
-- Reportes y búsquedas por fecha.
-- ----------------------------------------------------------

CREATE INDEX idx_pedido_fecha
ON pedido (fecha_pedido);

-- ----------------------------------------------------------
-- detalle_pedido
-- Obtención rápida de los productos de un pedido.
-- ----------------------------------------------------------

CREATE INDEX idx_detalle_pedido_pedido
ON detalle_pedido (pedido_id);

-- ----------------------------------------------------------
-- detalle_pedido
-- Consultas por producto.
-- ----------------------------------------------------------

CREATE INDEX idx_detalle_pedido_producto
ON detalle_pedido (producto_id);

-- ----------------------------------------------------------
-- unidad
-- Dashboard, Stock y búsquedas por estado.
-- ----------------------------------------------------------

CREATE INDEX idx_unidad_estado
ON unidad (estado);

-- ----------------------------------------------------------
-- unidad
-- Historial por producto.
-- ----------------------------------------------------------

CREATE INDEX idx_unidad_producto
ON unidad (producto_id);

-- ----------------------------------------------------------
-- unidad
-- Ventas por cliente.
-- ----------------------------------------------------------

CREATE INDEX idx_unidad_cliente
ON unidad (cliente_id);

-- ----------------------------------------------------------
-- unidad
-- Estadísticas por vendedor.
-- ----------------------------------------------------------

CREATE INDEX idx_unidad_vendedor
ON unidad (vendedor_id);

-- ----------------------------------------------------------
-- unidad
-- Control rápido por código / IMEI.
-- ----------------------------------------------------------

ALTER TABLE unidad
ADD CONSTRAINT uq_unidad_codigo
UNIQUE (codigo);

-- ----------------------------------------------------------
-- unidad
-- Reportes por fecha de retiro.
-- ----------------------------------------------------------

CREATE INDEX idx_unidad_fecha_retiro
ON unidad (fecha_retiro);

-- ----------------------------------------------------------
-- unidad
-- Reportes por fecha de entrega.
-- ----------------------------------------------------------

CREATE INDEX idx_unidad_fecha_entrega
ON unidad (fecha_entrega);

-- ----------------------------------------------------------
-- unidad
-- Unidades provenientes de un pedido.
-- ----------------------------------------------------------

CREATE INDEX idx_unidad_pedido
ON unidad (pedido_id);


-- Acceso cerrado por defecto: definir las políticas de usuarios antes de conectar la app.
ALTER TABLE public.proveedor ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.proveedor FROM anon, authenticated;
ALTER TABLE public.cliente ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.cliente FROM anon, authenticated;
ALTER TABLE public.vendedor ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.vendedor FROM anon, authenticated;
ALTER TABLE public.producto ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.producto FROM anon, authenticated;
ALTER TABLE public.pedido ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.pedido FROM anon, authenticated;
ALTER TABLE public.detalle_pedido ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.detalle_pedido FROM anon, authenticated;
ALTER TABLE public.unidad ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.unidad FROM anon, authenticated;

