BEGIN;

CREATE TABLE IF NOT EXISTS public.repartidor (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre varchar(120) NOT NULL,
 telefono varchar(50),
 observaciones text
);

DO $$
BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uq_repartidor_nombre') THEN
  ALTER TABLE public.repartidor ADD CONSTRAINT uq_repartidor_nombre UNIQUE(nombre);
 END IF;
END $$;

ALTER TABLE public.pedido ADD COLUMN IF NOT EXISTS repartidor_id bigint;
ALTER TABLE public.unidad ADD COLUMN IF NOT EXISTS repartidor_id bigint;

DO $$
BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_pedido_repartidor') THEN
  ALTER TABLE public.pedido ADD CONSTRAINT fk_pedido_repartidor FOREIGN KEY(repartidor_id) REFERENCES public.repartidor(id) ON DELETE RESTRICT;
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_unidad_repartidor') THEN
  ALTER TABLE public.unidad ADD CONSTRAINT fk_unidad_repartidor FOREIGN KEY(repartidor_id) REFERENCES public.repartidor(id) ON DELETE RESTRICT;
 END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_pedido_repartidor ON public.pedido(repartidor_id);
CREATE INDEX IF NOT EXISTS idx_unidad_repartidor ON public.unidad(repartidor_id);

ALTER TABLE public.repartidor ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE ON public.repartidor TO anon;
GRANT USAGE,SELECT ON SEQUENCE public.repartidor_id_seq TO anon;

DO $$
BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='repartidor' AND policyname='app_read') THEN
  CREATE POLICY app_read ON public.repartidor FOR SELECT TO anon USING(true);
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='repartidor' AND policyname='app_insert') THEN
  CREATE POLICY app_insert ON public.repartidor FOR INSERT TO anon WITH CHECK(true);
 END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='repartidor' AND policyname='app_update') THEN
  CREATE POLICY app_update ON public.repartidor FOR UPDATE TO anon USING(true) WITH CHECK(true);
 END IF;
END $$;

CREATE OR REPLACE FUNCTION public.pgl_assign_order_courier(p_id bigint,p_courier bigint) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 IF p_courier IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.repartidor WHERE id=p_courier) THEN
  RAISE EXCEPTION 'Selecciona un repartidor existente';
 END IF;
 UPDATE public.pedido SET repartidor_id=p_courier WHERE id=p_id;
 IF NOT FOUND THEN RAISE EXCEPTION 'Pedido inexistente'; END IF;
END $$;

CREATE OR REPLACE FUNCTION public.pgl_assign_sale_courier(p_unit bigint,p_courier bigint) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 IF p_courier IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.repartidor WHERE id=p_courier) THEN
  RAISE EXCEPTION 'Selecciona un repartidor existente';
 END IF;
 UPDATE public.unidad SET repartidor_id=p_courier WHERE id=p_unit AND estado IN ('REPARTO','ENTREGADA');
 IF NOT FOUND THEN RAISE EXCEPTION 'La unidad no tiene una venta activa'; END IF;
END $$;

CREATE OR REPLACE FUNCTION public.pgl_snapshot() RETURNS jsonb LANGUAGE sql STABLE SECURITY INVOKER SET search_path='' AS $$
 SELECT public.pgl_snapshot_alpha() || jsonb_build_object(
  'salePayments',coalesce((SELECT jsonb_agg(t ORDER BY registrado_en,id) FROM public.venta_abono t),'[]'::jsonb),
  'categories',coalesce((SELECT jsonb_agg(t ORDER BY nombre,id) FROM public.categorias t),'[]'::jsonb),
  'categoryCharacteristics',coalesce((SELECT jsonb_agg(t ORDER BY categoria_id,id) FROM public.categoria_caracteristica t),'[]'::jsonb),
  'supplierPayments',coalesce((SELECT jsonb_agg(t ORDER BY registrado_en,id) FROM public.proveedor_pago t),'[]'::jsonb),
  'couriers',coalesce((SELECT jsonb_agg(t ORDER BY id DESC) FROM public.repartidor t),'[]'::jsonb));
$$;

REVOKE ALL ON FUNCTION public.pgl_assign_order_courier(bigint,bigint),public.pgl_assign_sale_courier(bigint,bigint),public.pgl_snapshot() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.pgl_assign_order_courier(bigint,bigint),public.pgl_assign_sale_courier(bigint,bigint),public.pgl_snapshot() TO anon;
NOTIFY pgrst,'reload schema';

COMMIT;
